-- PostgreSQL DDL for case and file metadata.
-- status is intentionally TIMESTAMP to match the supplied schema.
-- case_id is assumed to be BIGINT because it references case_details.id.

CREATE TABLE case_details (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    case_description    VARCHAR(4000),
    case_category       VARCHAR(4000),
    assigned_officers   VARCHAR(4000),
    status              TIMESTAMP,
    date_added          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_modified       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    added_by            VARCHAR(200),
    modified_by         VARCHAR(200),

    CONSTRAINT pk_case_details PRIMARY KEY (id)
);

CREATE TABLE file_details (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    file_name           VARCHAR(4000) NOT NULL,
    case_id             BIGINT NOT NULL,
    extracted_content   TEXT,
    date_added          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_modified       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    added_by            VARCHAR(200),
    modified_by         VARCHAR(200),

    CONSTRAINT pk_file_details PRIMARY KEY (id),
    CONSTRAINT fk_file_details_case
        FOREIGN KEY (case_id)
        REFERENCES case_details (id)
);

CREATE INDEX idx_file_details_case_id
    ON file_details (case_id);

COMMENT ON TABLE case_details IS
    'Existing case metadata used to validate and associate file uploads.';

COMMENT ON COLUMN case_details.id IS 'Case identifier.';
COMMENT ON COLUMN case_details.case_description IS 'Description of the case.';
COMMENT ON COLUMN case_details.case_category IS 'Category assigned to the case.';
COMMENT ON COLUMN case_details.assigned_officers IS
    'Comma-separated list of officers assigned to the case for the prototype.';
COMMENT ON COLUMN case_details.status IS
    'Case status value represented as a timestamp in the supplied schema.';
COMMENT ON COLUMN case_details.date_added IS
    'Date and time when the case was added.';
COMMENT ON COLUMN case_details.date_modified IS
    'Date and time when the case was last modified.';
COMMENT ON COLUMN case_details.added_by IS
    'Username of the authenticated user who added the case.';
COMMENT ON COLUMN case_details.modified_by IS
    'Username of the authenticated user who last modified the case.';

COMMENT ON TABLE file_details IS
    'File metadata and content extracted from a case file.';

COMMENT ON COLUMN file_details.id IS 'File identifier.';
COMMENT ON COLUMN file_details.file_name IS 'Name of the stored file.';
COMMENT ON COLUMN file_details.case_id IS 'Identifier of the associated case.';
COMMENT ON COLUMN file_details.extracted_content IS
    'Content extracted from the file, including text, OCR, or a transcript.';
COMMENT ON COLUMN file_details.date_added IS
    'Date and time when the file was added.';
COMMENT ON COLUMN file_details.date_modified IS
    'Date and time when the file was last modified.';
COMMENT ON COLUMN file_details.added_by IS
    'Username of the authenticated user who added the file.';
COMMENT ON COLUMN file_details.modified_by IS
    'Username of the authenticated user who last modified the file.';
