INSERT INTO entity_attribute_details (
    id,
    attribute_type,
    attribute_data_type,
    attribute_description,
    entity_id,
    added_by,
    modified_by
)
VALUES
    (2001, 'full_name', 'string', 'Full name of the person.', 1001, 'system', 'system'),
    (2002, 'date_of_birth', 'date', 'Date of birth of the person, when known.', 1001, 'system', 'system'),
    (2003, 'email_address', 'string', 'Email address associated with the person.', 1001, 'system', 'system'),
    (2004, 'organization_name', 'string', 'Registered or commonly used organization name.', 1002, 'system', 'system'),
    (2005, 'registration_number', 'string', 'Official registration or incorporation number.', 1002, 'system', 'system'),
    (2006, 'location_name', 'string', 'Name used to identify the location.', 1003, 'system', 'system'),
    (2007, 'address', 'string', 'Postal or physical address of the location.', 1003, 'system', 'system'),
    (2008, 'document_number', 'string', 'Identifier assigned to the document.', 1004, 'system', 'system'),
    (2009, 'document_date', 'date', 'Date shown on or associated with the document.', 1004, 'system', 'system'),
    (2010, 'event_date', 'timestamp', 'Date and time when the event occurred.', 1005, 'system', 'system'),
    (2011, 'title', 'string', 'Title of the creative work.', 1006, 'system', 'system'),
    (2012, 'product_name', 'string', 'Name of the consumer product.', 1007, 'system', 'system'),
    (2013, 'number', 'string', 'Telephone number in its source or normalized form.', 1008, 'system', 'system'),
    (2014, 'country_code', 'string', 'Country calling code, when available.', 1008, 'system', 'system'),
    (2015, 'street_address', 'string', 'Street portion of the address.', 1009, 'system', 'system'),
    (2016, 'postal_code', 'string', 'Postal or ZIP code.', 1009, 'system', 'system'),
    (2017, 'date_value', 'date', 'Normalized calendar date.', 1010, 'system', 'system'),
    (2018, 'number_value', 'decimal', 'Normalized numeric value.', 1011, 'system', 'system'),
    (2019, 'amount', 'decimal', 'Numeric monetary amount.', 1012, 'system', 'system'),
    (2020, 'currency', 'string', 'ISO currency code or detected currency symbol.', 1012, 'system', 'system'),
    (2021, 'facility_name', 'string', 'Name of the facility.', 1013, 'system', 'system'),
    (2022, 'geopolitical_name', 'string', 'Name of the geopolitical area.', 1014, 'system', 'system'),
    (2023, 'group_name', 'string', 'Name of the nationality, religious, or political group.', 1015, 'system', 'system'),
    (2024, 'law_name', 'string', 'Name or title of the law or regulation.', 1016, 'system', 'system'),
    (2025, 'jurisdiction', 'string', 'Jurisdiction in which the law applies.', 1016, 'system', 'system'),
    (2026, 'language_name', 'string', 'Name of the language.', 1017, 'system', 'system'),
    (2027, 'percent_value', 'decimal', 'Normalized percentage value.', 1018, 'system', 'system'),
    (2028, 'quantity_value', 'decimal', 'Normalized numeric quantity.', 1019, 'system', 'system'),
    (2029, 'unit', 'string', 'Unit associated with the quantity.', 1019, 'system', 'system'),
    (2030, 'time_value', 'time', 'Normalized time value.', 1020, 'system', 'system'),
    (2031, 'email_address', 'string', 'Normalized email address.', 1021, 'system', 'system'),
    (2032, 'domain', 'string', 'Domain portion of the email address or URL.', 1021, 'system', 'system'),
    (2033, 'url', 'string', 'Normalized URL.', 1022, 'system', 'system'),
    (2034, 'ip_address', 'string', 'Normalized IPv4 or IPv6 address.', 1023, 'system', 'system'),
    (2035, 'ip_version', 'integer', 'Internet Protocol version, normally 4 or 6.', 1023, 'system', 'system'),
    (2036, 'registration_number', 'string', 'Vehicle registration or license plate number.', 1024, 'system', 'system'),
    (2037, 'vin', 'string', 'Vehicle identification number.', 1024, 'system', 'system'),
    (2038, 'make', 'string', 'Vehicle manufacturer.', 1024, 'system', 'system'),
    (2039, 'model', 'string', 'Vehicle model.', 1024, 'system', 'system'),
    (2040, 'account_number', 'string', 'Account identifier, stored or displayed according to security policy.', 1025, 'system', 'system'),
    (2041, 'account_type', 'string', 'Type or category of account.', 1025, 'system', 'system'),
    (2042, 'transaction_id', 'string', 'Identifier assigned to the transaction.', 1026, 'system', 'system'),
    (2043, 'transaction_date', 'timestamp', 'Date and time of the transaction.', 1026, 'system', 'system'),
    (2044, 'amount', 'decimal', 'Monetary amount of the transaction.', 1026, 'system', 'system'),
    (2045, 'currency', 'string', 'ISO currency code for the transaction amount.', 1026, 'system', 'system'),
    (2046, 'username', 'string', 'Normalized username or handle.', 1027, 'system', 'system'),
    (2047, 'platform', 'string', 'Application, service, or platform on which the username was observed.', 1027, 'system', 'system'),
    (2048, 'identifier_value', 'string', 'Normalized device identifier value.', 1028, 'system', 'system'),
    (2049, 'identifier_type', 'string', 'Identifier type, such as IMEI, IMSI, Android ID, IDFA, or serial number.', 1028, 'system', 'system'),
    (2050, 'wallet_address', 'string', 'Normalized wallet address.', 1029, 'system', 'system'),
    (2051, 'blockchain', 'string', 'Blockchain or network associated with the wallet.', 1029, 'system', 'system'),
    (2052, 'group_name', 'string', 'Group, channel, or community name.', 1030, 'system', 'system'),
    (2053, 'platform', 'string', 'Application or service hosting the group.', 1030, 'system', 'system'),
    (2054, 'external_group_id', 'string', 'Platform-specific group identifier.', 1030, 'system', 'system'),
    (2055, 'device_name', 'string', 'Human-readable device name.', 1031, 'system', 'system'),
    (2056, 'device_type', 'string', 'Device category, such as phone, laptop, or tablet.', 1031, 'system', 'system'),
    (2057, 'source_device_id', 'string', 'Stable identifier assigned to the source device.', 1031, 'system', 'system'),
    (2058, 'artefact_id', 'string', 'Stable identifier for provenance drill-down.', 1032, 'system', 'system'),
    (2059, 'artefact_type', 'string', 'Type of evidential artefact.', 1032, 'system', 'system'),
    (2060, 'source_path', 'string', 'Source location or path of the artefact.', 1032, 'system', 'system'),
    (2061, 'content_hash', 'string', 'Cryptographic hash used to verify the source artefact.', 1032, 'system', 'system'),
    (2062, 'canonical_name', 'string', 'Investigator-visible name assigned to the consolidated identity.', 1033, 'system', 'system'),
    (2063, 'resolution_status', 'string', 'Resolution state, such as proposed, confirmed, rejected, or conflicted.', 1033, 'system', 'system')
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('entity_attribute_details', 'id'),
    (SELECT MAX(id) FROM entity_attribute_details)
);
