CREATE TABLE entity_details (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    entity_name         VARCHAR(4000),
    label               VARCHAR(200),
    entity_description  VARCHAR(4000),
    is_standard         VARCHAR(1),
    date_added          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_modified       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    added_by            VARCHAR(200),
    modified_by         VARCHAR(200),

    CONSTRAINT pk_entity_details PRIMARY KEY (id),
    CONSTRAINT ck_entity_details_name_uppercase
        CHECK (entity_name = UPPER(entity_name)),
    CONSTRAINT ck_entity_details_standard
        CHECK (is_standard IN ('Y', 'N'))
);
