CREATE TABLE entity_attribute_details (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    attribute_type         VARCHAR(200),
    attribute_data_type    VARCHAR(200),
    attribute_description  VARCHAR(4000),
    entity_id              BIGINT NOT NULL,
    date_added             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_modified          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    added_by               VARCHAR(200),
    modified_by            VARCHAR(200),

    CONSTRAINT pk_entity_attribute_details PRIMARY KEY (id),
    CONSTRAINT fk_entity_attribute_entity
        FOREIGN KEY (entity_id)
        REFERENCES entity_details (id)
);

CREATE INDEX idx_entity_attribute_entity
    ON entity_attribute_details (entity_id);
