CREATE TABLE relationship_details (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    relationship_name         VARCHAR(4000),
    relationship_description  VARCHAR(4000),
    is_standard               VARCHAR(1),
    date_added                TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_modified             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    added_by                  VARCHAR(200),
    modified_by               VARCHAR(200),

    CONSTRAINT pk_relationship_details PRIMARY KEY (id),
    CONSTRAINT ck_relationship_standard
        CHECK (is_standard IN ('Y', 'N'))
);
