CREATE TABLE relationship_attribute_details (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    attribute_type         VARCHAR(200),
    relationship_id        BIGINT NOT NULL,
    attribute_description  VARCHAR(4000),
    attribute_data_type    VARCHAR(200),
    date_added             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_modified          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    added_by               VARCHAR(200),
    modified_by            VARCHAR(200),

    CONSTRAINT pk_relationship_attribute_details PRIMARY KEY (id),
    CONSTRAINT fk_relationship_attribute_rel
        FOREIGN KEY (relationship_id)
        REFERENCES relationship_details (id)
);

CREATE INDEX idx_relationship_attribute_rel
    ON relationship_attribute_details (relationship_id);
