-- Job and per-file execution state for the Entity Extraction Jobs screen.

CREATE TABLE entity_extraction_job (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    case_id             BIGINT NOT NULL,
    job_key             VARCHAR(500) NOT NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'QUEUED',
    trigger_type        VARCHAR(30) NOT NULL DEFAULT 'MANUAL',
    extractor_name      VARCHAR(500) NOT NULL,
    extractor_version   VARCHAR(200),
    progress_percent    NUMERIC(5,2) NOT NULL DEFAULT 0,
    files_total         INTEGER NOT NULL DEFAULT 0,
    files_completed     INTEGER NOT NULL DEFAULT 0,
    entities_extracted  INTEGER NOT NULL DEFAULT 0,
    relationships_extracted INTEGER NOT NULL DEFAULT 0,
    warnings_count      INTEGER NOT NULL DEFAULT 0,
    error_code          VARCHAR(200),
    error_message       TEXT,
    requested_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    parameters          JSONB NOT NULL DEFAULT '{}'::JSONB,
    date_added          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modified       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    added_by            VARCHAR(200),
    modified_by         VARCHAR(200),
    CONSTRAINT pk_entity_extraction_job PRIMARY KEY (id),
    CONSTRAINT fk_extraction_job_case FOREIGN KEY (case_id) REFERENCES case_details (id),
    CONSTRAINT uq_extraction_job_key UNIQUE (job_key),
    CONSTRAINT ck_extraction_job_status CHECK (status IN
        ('QUEUED','RUNNING','COMPLETED','PARTIAL','FAILED','CANCELLED')),
    CONSTRAINT ck_extraction_trigger CHECK (trigger_type IN
        ('MANUAL','FILE_UPLOAD','RETRY','SCHEDULED')),
    CONSTRAINT ck_extraction_progress CHECK (progress_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_extraction_counts CHECK (
        files_total >= 0 AND files_completed >= 0
        AND entities_extracted >= 0 AND relationships_extracted >= 0
        AND warnings_count >= 0
    )
);

CREATE INDEX idx_extraction_job_case_status
    ON entity_extraction_job (case_id, status, requested_at DESC);

CREATE TABLE entity_extraction_job_file (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    job_id              BIGINT NOT NULL,
    file_id             BIGINT NOT NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'QUEUED',
    input_hash          VARCHAR(256),
    extractor_version   VARCHAR(200),
    reused_previous_result BOOLEAN NOT NULL DEFAULT FALSE,
    previous_job_file_id BIGINT,
    entities_extracted  INTEGER NOT NULL DEFAULT 0,
    relationships_extracted INTEGER NOT NULL DEFAULT 0,
    warnings_count      INTEGER NOT NULL DEFAULT 0,
    error_code          VARCHAR(200),
    error_message       TEXT,
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    date_added          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modified       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_extraction_job_file PRIMARY KEY (id),
    CONSTRAINT fk_job_file_job FOREIGN KEY (job_id) REFERENCES entity_extraction_job (id) ON DELETE CASCADE,
    CONSTRAINT fk_job_file_file FOREIGN KEY (file_id) REFERENCES file_details (id),
    CONSTRAINT fk_job_file_previous FOREIGN KEY (previous_job_file_id) REFERENCES entity_extraction_job_file (id),
    CONSTRAINT uq_extraction_job_file UNIQUE (job_id, file_id),
    CONSTRAINT ck_job_file_status CHECK (status IN
        ('QUEUED','RUNNING','COMPLETED','SKIPPED','FAILED','CANCELLED'))
);

CREATE INDEX idx_extraction_job_file_job ON entity_extraction_job_file (job_id, status);
CREATE INDEX idx_extraction_job_file_hash ON entity_extraction_job_file (file_id, input_hash, extractor_version);

