CREATE TABLE extracted_entity_relationship (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    case_id            BIGINT NOT NULL,
    job_id             BIGINT,
    job_file_id        BIGINT,
    file_id            BIGINT,
    extracted_details  JSONB,
    schema_version     VARCHAR(50),
    extractor_version  VARCHAR(200),
    processing_status  VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',
    is_standard        VARCHAR(1),
    date_added         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    date_modified      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    added_by           VARCHAR(200),
    modified_by        VARCHAR(200),

    CONSTRAINT pk_extracted_entity_relationship PRIMARY KEY (id),
    CONSTRAINT fk_extracted_relationship_case
        FOREIGN KEY (case_id)
        REFERENCES case_details (id),
    CONSTRAINT fk_extracted_relationship_job
        FOREIGN KEY (job_id)
        REFERENCES entity_extraction_job (id),
    CONSTRAINT fk_extracted_relationship_job_file
        FOREIGN KEY (job_file_id)
        REFERENCES entity_extraction_job_file (id),
    CONSTRAINT fk_extracted_relationship_file
        FOREIGN KEY (file_id)
        REFERENCES file_details (id),
    CONSTRAINT ck_extracted_relationship_standard
        CHECK (is_standard IN ('Y', 'N')),
    CONSTRAINT ck_extracted_relationship_status
        CHECK (processing_status IN
            ('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED'))
);

CREATE INDEX idx_extracted_relationship_case
    ON extracted_entity_relationship (case_id);

CREATE INDEX idx_extracted_relationship_job
    ON extracted_entity_relationship (job_id);

CREATE INDEX idx_extracted_relationship_job_file
    ON extracted_entity_relationship (job_file_id);

CREATE INDEX idx_extracted_relationship_file
    ON extracted_entity_relationship (file_id);
