-- Device/file provenance and evidence metadata used by the Evidence,
-- Extraction Result Explorer, and Evidence & Quality Review screens.

CREATE TABLE device_details (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    case_id             BIGINT NOT NULL,
    external_device_id  VARCHAR(500),
    device_name         VARCHAR(1000) NOT NULL,
    device_type         VARCHAR(100),
    manufacturer        VARCHAR(500),
    model               VARCHAR(500),
    serial_number       VARCHAR(500),
    acquisition_method  VARCHAR(200),
    acquired_at         TIMESTAMPTZ,
    metadata            JSONB NOT NULL DEFAULT '{}'::JSONB,
    date_added          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modified       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    added_by            VARCHAR(200),
    modified_by         VARCHAR(200),
    CONSTRAINT pk_device_details PRIMARY KEY (id),
    CONSTRAINT fk_device_case FOREIGN KEY (case_id) REFERENCES case_details (id),
    CONSTRAINT uq_device_external UNIQUE (case_id, external_device_id)
);

CREATE INDEX idx_device_case ON device_details (case_id);

CREATE TABLE file_device_link (
    file_id             BIGINT NOT NULL,
    device_id           BIGINT NOT NULL,
    is_primary          BOOLEAN NOT NULL DEFAULT FALSE,
    date_added          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    added_by            VARCHAR(200),
    CONSTRAINT pk_file_device_link PRIMARY KEY (file_id, device_id),
    CONSTRAINT fk_file_device_file FOREIGN KEY (file_id) REFERENCES file_details (id) ON DELETE CASCADE,
    CONSTRAINT fk_file_device_device FOREIGN KEY (device_id) REFERENCES device_details (id) ON DELETE CASCADE
);

CREATE INDEX idx_file_device_device ON file_device_link (device_id);

CREATE TABLE evidence_set_details (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    case_id             BIGINT NOT NULL,
    evidence_set_key    VARCHAR(500) NOT NULL,
    name                VARCHAR(1000) NOT NULL,
    description         TEXT,
    classification      VARCHAR(100),
    metadata            JSONB NOT NULL DEFAULT '{}'::JSONB,
    date_added          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modified       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    added_by            VARCHAR(200),
    modified_by         VARCHAR(200),
    CONSTRAINT pk_evidence_set PRIMARY KEY (id),
    CONSTRAINT fk_evidence_set_case FOREIGN KEY (case_id) REFERENCES case_details (id),
    CONSTRAINT uq_evidence_set_key UNIQUE (case_id, evidence_set_key)
);

CREATE INDEX idx_evidence_set_case ON evidence_set_details (case_id);

CREATE TABLE evidence_record_details (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    case_id             BIGINT NOT NULL,
    file_id             BIGINT NOT NULL,
    device_id           BIGINT,
    evidence_set_id     BIGINT,
    external_record_id  VARCHAR(1000) NOT NULL,
    record_type         VARCHAR(200) NOT NULL,
    extracted_text      TEXT,
    extracted_metadata  JSONB NOT NULL DEFAULT '{}'::JSONB,
    source_span         TEXT,
    start_offset        BIGINT,
    end_offset          BIGINT,
    extraction_method   VARCHAR(500),
    confidence          NUMERIC(6,5),
    observed_at         TIMESTAMPTZ,
    content_protected   BOOLEAN NOT NULL DEFAULT TRUE,
    content_hash        VARCHAR(256),
    date_added          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modified       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    added_by            VARCHAR(200),
    modified_by         VARCHAR(200),
    CONSTRAINT pk_evidence_record PRIMARY KEY (id),
    CONSTRAINT fk_evidence_record_case FOREIGN KEY (case_id) REFERENCES case_details (id),
    CONSTRAINT fk_evidence_record_file FOREIGN KEY (file_id) REFERENCES file_details (id),
    CONSTRAINT fk_evidence_record_device FOREIGN KEY (device_id) REFERENCES device_details (id),
    CONSTRAINT fk_evidence_record_set FOREIGN KEY (evidence_set_id) REFERENCES evidence_set_details (id),
    CONSTRAINT uq_evidence_record UNIQUE (case_id, file_id, external_record_id),
    CONSTRAINT ck_evidence_offsets CHECK (
        (start_offset IS NULL AND end_offset IS NULL)
        OR (start_offset >= 0 AND end_offset >= start_offset)
    ),
    CONSTRAINT ck_evidence_confidence CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1)
);

CREATE INDEX idx_evidence_record_case ON evidence_record_details (case_id);
CREATE INDEX idx_evidence_record_file ON evidence_record_details (file_id);
CREATE INDEX idx_evidence_record_device ON evidence_record_details (device_id);
CREATE INDEX idx_evidence_record_observed ON evidence_record_details (case_id, observed_at);

