-- Review queue for extracted entities, relationships, and evidence records.

CREATE TABLE extraction_quality_review (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    case_id             BIGINT NOT NULL,
    job_id              BIGINT,
    job_file_id         BIGINT,
    extracted_result_id BIGINT,
    evidence_record_id  BIGINT,
    subject_type        VARCHAR(30) NOT NULL,
    subject_id          VARCHAR(500) NOT NULL,
    review_status       VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    quality_score       NUMERIC(6,5),
    confidence          NUMERIC(6,5),
    has_warning         BOOLEAN NOT NULL DEFAULT FALSE,
    has_contradiction   BOOLEAN NOT NULL DEFAULT FALSE,
    warning_codes       JSONB NOT NULL DEFAULT '[]'::JSONB,
    reviewer_comment    TEXT,
    assigned_to         VARCHAR(200),
    reviewed_by         VARCHAR(200),
    reviewed_at         TIMESTAMPTZ,
    date_added          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modified       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    added_by            VARCHAR(200),
    modified_by         VARCHAR(200),
    CONSTRAINT pk_extraction_quality_review PRIMARY KEY (id),
    CONSTRAINT fk_quality_case FOREIGN KEY (case_id) REFERENCES case_details (id),
    CONSTRAINT fk_quality_job FOREIGN KEY (job_id) REFERENCES entity_extraction_job (id),
    CONSTRAINT fk_quality_job_file FOREIGN KEY (job_file_id) REFERENCES entity_extraction_job_file (id),
    CONSTRAINT fk_quality_result FOREIGN KEY (extracted_result_id) REFERENCES extracted_entity_relationship (id),
    CONSTRAINT fk_quality_evidence FOREIGN KEY (evidence_record_id) REFERENCES evidence_record_details (id),
    CONSTRAINT uq_quality_subject UNIQUE (case_id, subject_type, subject_id),
    CONSTRAINT ck_quality_subject_type CHECK (subject_type IN ('ENTITY','RELATIONSHIP','EVIDENCE')),
    CONSTRAINT ck_quality_status CHECK (review_status IN
        ('PENDING','IN_REVIEW','ACCEPTED','REJECTED','NEEDS_CORRECTION')),
    CONSTRAINT ck_quality_score CHECK (quality_score IS NULL OR quality_score BETWEEN 0 AND 1),
    CONSTRAINT ck_quality_confidence CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1)
);

CREATE INDEX idx_quality_review_queue
    ON extraction_quality_review (case_id, review_status, has_warning, has_contradiction);

