-- Candidate comparison and reversible decision history for Entity Resolution Review.
-- canonical_entity_id values point to Neo4j and intentionally have no SQL FK.

CREATE TABLE entity_resolution_candidate (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    case_id             BIGINT NOT NULL,
    candidate_key       VARCHAR(500) NOT NULL,
    source_entity_id    VARCHAR(500) NOT NULL,
    target_entity_id    VARCHAR(500) NOT NULL,
    source_label        VARCHAR(2000),
    target_label        VARCHAR(2000),
    entity_type         VARCHAR(100),
    match_score         NUMERIC(6,5) NOT NULL,
    resolution_method   VARCHAR(500),
    matching_attributes JSONB NOT NULL DEFAULT '{}'::JSONB,
    conflicting_attributes JSONB NOT NULL DEFAULT '{}'::JSONB,
    evidence_summary    JSONB NOT NULL DEFAULT '{}'::JSONB,
    status              VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    date_added          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modified       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    added_by            VARCHAR(200),
    modified_by         VARCHAR(200),
    CONSTRAINT pk_resolution_candidate PRIMARY KEY (id),
    CONSTRAINT fk_resolution_candidate_case FOREIGN KEY (case_id) REFERENCES case_details (id),
    CONSTRAINT uq_resolution_candidate UNIQUE (case_id, candidate_key),
    CONSTRAINT ck_resolution_score CHECK (match_score BETWEEN 0 AND 1),
    CONSTRAINT ck_resolution_candidate_status CHECK (status IN
        ('PENDING','APPROVED','REJECTED','MERGED','CONFLICTED','SUPERSEDED')),
    CONSTRAINT ck_resolution_distinct_entities CHECK (source_entity_id <> target_entity_id)
);

CREATE INDEX idx_resolution_candidate_queue
    ON entity_resolution_candidate (case_id, status, match_score DESC);

CREATE TABLE entity_resolution_decision (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    candidate_id        BIGINT NOT NULL,
    action              VARCHAR(30) NOT NULL,
    resulting_entity_id VARCHAR(500),
    reason_code         VARCHAR(200),
    comment             TEXT,
    previous_state      JSONB,
    resulting_state     JSONB,
    reversible          BOOLEAN NOT NULL DEFAULT TRUE,
    reversed_decision_id BIGINT,
    decided_by          VARCHAR(200) NOT NULL,
    decided_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_resolution_decision PRIMARY KEY (id),
    CONSTRAINT fk_resolution_decision_candidate FOREIGN KEY (candidate_id) REFERENCES entity_resolution_candidate (id),
    CONSTRAINT fk_resolution_reversed_decision FOREIGN KEY (reversed_decision_id) REFERENCES entity_resolution_decision (id),
    CONSTRAINT ck_resolution_action CHECK (action IN
        ('APPROVE_MERGE','REJECT_MERGE','MARK_CONFLICT','UNDO_MERGE'))
);

CREATE INDEX idx_resolution_decision_candidate
    ON entity_resolution_decision (candidate_id, decided_at DESC);

