-- Notes and incorrect-relationship reports referenced by graph detail actions.

CREATE TABLE investigator_note (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    case_id             BIGINT NOT NULL,
    subject_type        VARCHAR(30) NOT NULL,
    subject_id          VARCHAR(500) NOT NULL,
    note_text           TEXT NOT NULL,
    created_by          VARCHAR(200) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_by         VARCHAR(200),
    modified_at         TIMESTAMPTZ,
    CONSTRAINT pk_investigator_note PRIMARY KEY (id),
    CONSTRAINT fk_investigator_note_case FOREIGN KEY (case_id) REFERENCES case_details (id),
    CONSTRAINT ck_investigator_note_subject CHECK (subject_type IN
        ('CASE','FILE','EVIDENCE','ENTITY','RELATIONSHIP','EXTRACTION_JOB')),
    CONSTRAINT ck_investigator_note_text CHECK (length(btrim(note_text)) > 0)
);

CREATE INDEX idx_investigator_note_subject
    ON investigator_note (case_id, subject_type, subject_id, created_at DESC);

CREATE TABLE relationship_review_report (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    case_id             BIGINT NOT NULL,
    relationship_id     VARCHAR(500) NOT NULL,
    report_status       VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    reason_code         VARCHAR(100) NOT NULL,
    description         TEXT,
    supporting_evidence JSONB NOT NULL DEFAULT '[]'::JSONB,
    reported_by         VARCHAR(200) NOT NULL,
    reported_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_by         VARCHAR(200),
    resolved_at         TIMESTAMPTZ,
    resolution_comment  TEXT,
    CONSTRAINT pk_relationship_review_report PRIMARY KEY (id),
    CONSTRAINT fk_relationship_report_case FOREIGN KEY (case_id) REFERENCES case_details (id),
    CONSTRAINT ck_relationship_report_status CHECK (report_status IN
        ('OPEN','IN_REVIEW','CONFIRMED_INCORRECT','DISMISSED','CORRECTED')),
    CONSTRAINT ck_relationship_report_reason CHECK (reason_code IN
        ('WRONG_SOURCE','WRONG_TARGET','WRONG_TYPE','INSUFFICIENT_EVIDENCE',
         'INCORRECT_TIME_RANGE','DUPLICATE','OTHER'))
);

CREATE INDEX idx_relationship_report_queue
    ON relationship_review_report (case_id, report_status, reported_at DESC);

